export const FETCHING_START = "FETCHING_START";
export const FETCHING_SUCCESSFULL = "FETCHING_SUCCESSFULL";
export const FETCHING_ERROR = "FETCHING_ERROR";
export const USERS_DATA = "USERS_DATA";
export const LOGGEDIN_USER = "LOGGEDIN_USER";
